### ISSUE TITLE
Tests fail with internal error

### ISSUE THREAD

**Issue by yurivict** [wntrblm/nox#689] opened 2023-02-05 17:25 UTC
### Current Behavior

```
===>   py39-nox-2022.11.21 depends on file: /usr/local/bin/python3.9 - found
cd /usr/ports/devel/py-nox/work-py39/nox-2022.11.21 && /usr/bin/env XDG_DATA_HOME=/usr/ports/devel/py-nox/work-py39  XDG_CONFIG_HOME=/usr/ports/devel/py-nox/work-py39  XDG_CACHE_HOME=/usr/ports/devel/py-nox/work-py39/.cache  HOME=/usr/ports/devel/py-nox/work-py39 PATH=/usr/local/libexec/ccache:/usr/ports/devel/py-nox/work-py39/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/usr/ports/devel/py-nox/work-py39/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  MANPREFIX="/usr/local" CCACHE_DIR="/tmp/.ccache" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" /usr/local/bin/python3.9 -m pytest -k '' -rs -v -o addopts= 
========================================================================================== test session starts ==========================================================================================
platform freebsd13 -- Python 3.9.16, pytest-7.2.0, pluggy-1.0.0 -- /usr/local/bin/python3.9
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/usr/ports/devel/py-nox/work-py39/nox-2022.11.21/.hypothesis/examples')
Using --randomly-seed=1315006708
rootdir: /usr/ports/devel/py-nox/work-py39/nox-2022.11.21, configfile: pyproject.toml, testpaths: tests
plugins: hypothesis-6.58.0, asyncio-0.20.3, trio-0.8.0, cov-2.9.0, flaky-3.7.0, xdist-2.5.0, flake8-1.1.1, forked-1.4.0, anyio-3.6.2, randomly-3.12.0, timeout-2.1.0, rerunfailures-10.1, env-0.6.2, freezegun-0.4.2, mock-1.10.4, nbval-0.10.0
asyncio: mode=strict
collected 437 items / 1 error                                                                                                                                                                           
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 334, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 667, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pytest_freezegun.py", line 55, in pytest_collection_modifyitems
INTERNALERROR>     if get_closest_marker(item, MARKER_NAME):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pytest_freezegun.py", line 17, in get_closest_marker
INTERNALERROR>     if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/version.py", line 55, in __init__
INTERNALERROR>     warnings.warn(
INTERNALERROR> DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

=========================================================================================== 1 error in 1.52s ============================================================================================
*** Error code 3
```

Version: 2022.11.21
Python-3.9
FreeBSD 13.1

### Environment

```Markdown
- OS:
- Python:
- Nox:
```

**Comment by FollowTheProcess** [comment] 2023-02-11 10:23
It looks as if you've got a bit of an unusual setup? That pytest command in particular looks pretty gnarly. This looks like a pytest thing to me? Nothing in that traceback mentions Nox as far as I can see. Nox basically just shells out to whatever command you have in `session.run` so you may have better luck raising this with https://github.com/pytest-dev/pytest

**Comment by DiddiLeija** [comment] 2023-10-21 02:59
Based in the command output, I'd say this is not a Nox issue (just like @FollowTheProcess noted a while back), so I'll close this issue.

@yurivict if this is actually a Nox issue, please let us know and provide more details / a reproducible environment ;)

**Closed by DiddiLeija** 2023-10-21 02:59 UTC
Labels: bug
